class Period {
  List period = [
    {
      "caliber": "5.56mm",
      "number": "1",
      "feedDevice": "30 rounds plastic box magazine",
      "rateOfFire": "450-650rpm",
      "cpkHexColor": "FFFFFF",
      "sightingSystem": "1.5x or 3x Optical Scope Laser Aiming Device",
      "origin": "Singapore",
      "barrelLength": "508mm",
      "groupBlock": "Infantry Section",
      "muzzelVelocity": "970m/s",
      "heavyMass": "3.98kg",
      "name": "SAR-21", // full name of weapon
      "fullLength": "805mm",
      "symbol": "SAR-21", //used to be symbol
      "effectiveRange": "460m",
      "yearInvented": "1996"
    },
    {
      "caliber": "5.56mm",
      "number": "2",
      "feedDevice":
          "100-round drum magazine or 30-round STANAG M16 box magazine",
      "rateOfFire": "400-600rpm",
      "cpkHexColor": "D9FFFF",
      "sightingSystem": "Rear aperture sight and front post 472mm sight radius",
      "origin": "Singapore",
      "barrelLength": "508mm",
      "groupBlock": "Infantry Section",
      "muzzelVelocity": "970m/s",
      "heavyMass": "4.90kg",
      "name": "SAW",
      "fullLength": "1024mm",
      "symbol": "SAW",
      "effectiveRange": "100-1200m sight adjustments",
      "yearInvented": "1978"
    },
    {
      "caliber": "7.62mm",
      "number": "3",
      "feedDevice": "?",
      "rateOfFire": "1200rpm",
      "cpkHexColor": "CC80FF",
      "sightingSystem": "?",
      "origin": "USA",
      "barrelLength": "630mm",
      "groupBlock": "Infantry Platoon",
      "muzzelVelocity": "850m/s",
      "heavyMass": "11.79kg",
      "name": "GPMG",
      "fullLength": "XX",
      "symbol": "GPMG", //used to be symbol,
      "effectiveRange": "XX",
      "yearInvented": "XXXX"
    },
    {
      "caliber": "?",
      "number": "4",
      "feedDevice": "?",
      "rateOfFire": "XX",
      "cpkHexColor": "C2FF00",
      "sightingSystem": "?",
      "origin": "?",
      "barrelLength": "305mm",
      "groupBlock": "Infantry Section",
      "muzzelVelocity": "XX",
      "heavyMass": "XX",
      "name": "M203",
      "fullLength": "XX",
      "symbol": "M203", //used to be symbol,
      "effectiveRange": "XX",
      "yearInvented": "XXXX"
    },
    {
      "caliber": "?",
      "number": "5",
      "feedDevice": "?",
      "rateOfFire": "XX",
      "cpkHexColor": "FFB5B5",
      "sightingSystem": "?",
      "origin": "?",
      "barrelLength": "XX",
      "groupBlock": "Automatic Grenade Launcher",
      "muzzelVelocity": "XX",
      "heavyMass": "XX",
      "name": "AGL",
      "fullLength": "XX",
      "symbol": "STK 40 AGL", //used to be symbol,
      "effectiveRange": "XX",
      "yearInvented": "XXXX"
    },
    {
      "caliber": "?",
      "number": "6",
      "feedDevice": "?",
      "rateOfFire": "XX",
      "cpkHexColor": "909090",
      "sightingSystem": "?",
      "origin": "?",
      "barrelLength": "XX",
      "groupBlock": "Sniper",
      "muzzelVelocity": "XX",
      "heavyMass": "XX",
      "name": "M110",
      "fullLength": "XX",
      "symbol": "M110", //used to be symbol,
      "effectiveRange": "XX",
      "yearInvented": "XXXX"
    },
    {
      "caliber": "?",
      "number": "7",
      "feedDevice": "?",
      "rateOfFire": "XX",
      "cpkHexColor": "3050F8",
      "sightingSystem": "?",
      "origin": "?",
      "barrelLength": "XX",
      "groupBlock": "Infantry Section",
      "muzzelVelocity": "XX",
      "heavyMass": "XX",
      "name": "M16",
      "fullLength": "XX",
      "symbol": "M16", //used to be symbol,
      "effectiveRange": "XX",
      "yearInvented": "XXXX"
    },
  ];
}
